eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8090
spring:
  application:
    name: zuul-server
zuul:
  routes:
    alumnos:
      path: /api/alumnos/**
      service-id: servicio-alumnos
    cursos:
      path: /api/cursos/**
      service-id: servicio-cursos  
    configuracion:
      path: /api/configuracion/**
      service-id: servicio-configuracion  
    examenes:
      path: /api/examenes/**
      service-id: servicio-examenes    
