eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka   
server:
  port: 8091
spring:
  application:
    name: spring-gateway-server
  profiles:
    active:
    - dev
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
               